# Generated by Django 4.2.19 on 2025-03-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('J', 'Jack'), ('Q', 'Queen'), ('K', 'King'), ('A', 'Ace')], max_length=5)),
                ('suit', models.CharField(choices=[('Hearts', 'Hearts'), ('Diamonds', 'Diamonds'), ('Clubs', 'Clubs'), ('Spades', 'Spades')], max_length=10)),
                ('is_dealt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished')], default='STARTED', max_length=20)),
                ('player_score', models.IntegerField(default=0)),
                ('dealer_score', models.IntegerField(default=0)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('dealer_hand', models.ManyToManyField(related_name='dealer_cards', to='blackjack.card')),
                ('player_hand', models.ManyToManyField(related_name='player_cards', to='blackjack.card')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='blackjack.card')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='blackjack.game')),
            ],
        ),
    ]
